package main

import (
	"encoding/base64"
	"io"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strings"
	"testing"
	"time"
)

// TestSignRequestMatchesReferenceVector pins the signer to the exact canonical
// request and signature produced by the CodeArts Agent extension's own
// SDK-HMAC-SHA256 implementation. The expected values were generated by running
// that extracted implementation over the same inputs.
func TestSignRequestMatchesReferenceVector(t *testing.T) {
	const (
		wantSignature = "0093888a0805c8535df7212bd72024fea1570eabb927853f44a4d0827204bac4"
		wantSigned    = "content-type;plugin-name;x-domain-id;x-language;x-sdk-date;x-security-token"
		wantCanonical = "POST\n/api/v2/chat/completions/\n\n" +
			"content-type:application/json\n" +
			"plugin-name:snap_vscode\n" +
			"x-domain-id:dom\n" +
			"x-language:en-us\n" +
			"x-sdk-date:20260102T030405Z\n" +
			"x-security-token:tok\n" +
			"\n" + wantSigned + "\n" +
			"78b0e11c6754fc9671c2034f4a068d3a0e53c1c22a5a33900dd46bc8cd9136f3"
	)

	headers := map[string]string{
		"content-type":     "application/json",
		"X-Security-Token": "tok",
		"X-Domain-Id":      "dom",
		"plugin-name":      "snap_vscode",
		"X-Language":       "en-us",
		"X-Sdk-Date":       "20260102T030405Z",
	}
	cred := &credential{
		AccessKeyID:     "AKIDEXAMPLE",
		SecretAccessKey: "secret",
		SecurityToken:   "tok",
		DomainID:        "dom",
	}

	// Sign without injecting host so the header set matches the reference.
	signed, errSign := signRequest("POST",
		"https://snap-access.cn-north-4.myhuaweicloud.com/api/v2/chat/completions",
		headers, []byte(`{"model":"x"}`), cred, false)
	if errSign != nil {
		t.Fatalf("signRequest returned an error: %v", errSign)
	}

	authorization := signed[headerAuth]
	if !strings.Contains(authorization, "Signature="+wantSignature) {
		t.Fatalf("signature mismatch:\n got %q\nwant signature %q", authorization, wantSignature)
	}
	if !strings.Contains(authorization, "SignedHeaders="+wantSigned) {
		t.Fatalf("signed headers mismatch:\n got %q\nwant %q", authorization, wantSigned)
	}

	// Re-derive the canonical request to confirm the intermediate value too.
	canonical := strings.Join([]string{
		"POST",
		canonicalURI("/api/v2/chat/completions"),
		canonicalQueryString(url.Values{}),
		"content-type:application/json\n" +
			"plugin-name:snap_vscode\n" +
			"x-domain-id:dom\n" +
			"x-language:en-us\n" +
			"x-sdk-date:20260102T030405Z\n" +
			"x-security-token:tok\n",
		wantSigned,
		sha256Hex([]byte(`{"model":"x"}`)),
	}, "\n")
	if canonical != wantCanonical {
		t.Fatalf("canonical request mismatch:\n got %q\nwant %q", canonical, wantCanonical)
	}
}

func TestCanonicalURIEscapesSegmentsAndAddsTrailingSlash(t *testing.T) {
	cases := map[string]string{
		"/api/v2/chat/completions": "/api/v2/chat/completions/",
		"/v1/chat/chat":            "/v1/chat/chat/",
		"/a b/c":                   "/a%20b/c/",
		"/already/":                "/already/",
		"":                         "/",
	}
	for input, want := range cases {
		if got := canonicalURI(input); got != want {
			t.Errorf("canonicalURI(%q) = %q, want %q", input, got, want)
		}
	}
}

func TestCanonicalQueryStringSortsAndEscapes(t *testing.T) {
	values := url.Values{}
	values.Set("ticket_id", "abc-123")
	values.Set("secret", "a b/c")
	values.Add("multi", "z")
	values.Add("multi", "a")

	got := canonicalQueryString(values)
	want := "multi=a&multi=z&secret=a%20b%2Fc&ticket_id=abc-123"
	if got != want {
		t.Fatalf("canonicalQueryString = %q, want %q", got, want)
	}
}

func TestRequestCarriesBody(t *testing.T) {
	if !requestCarriesBody("POST") || !requestCarriesBody("put") {
		t.Fatal("POST and PUT must be treated as body bearing")
	}
	if requestCarriesBody("GET") || requestCarriesBody("DELETE") {
		t.Fatal("GET and DELETE must sign the empty-body digest")
	}
}

func TestSignRequestRejectsIncompleteCredential(t *testing.T) {
	_, errSign := signRequest("POST", "https://example.invalid/x", nil, nil, &credential{AccessKeyID: "only-ak"}, false)
	if errSign == nil {
		t.Fatal("expected an error for a credential without a secret key")
	}
}

// The real CPA host assigns the plugin's header map directly to http.Request.
// A lower-case "host" key bypasses net/http's canonical Host exclusion and is
// sent in addition to the built-in Host header, which an HTTP/1 server rejects
// before its handler runs. A mocked host callback cannot catch this regression.
func TestHostSignedRequestSurvivesCPAHTTPSerialization(t *testing.T) {
	for _, suppliedHostKey := range []string{"", "host", "Host", "hOsT"} {
		name := suppliedHostKey
		if name == "" {
			name = "injected-host"
		}
		t.Run(name, func(t *testing.T) {
			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				if r.Host == "" || !strings.Contains(r.Header.Get("Authorization"), "SignedHeaders=host;x-sdk-date;x-security-token,") || r.Header.Get("X-Security-Token") != "fixture-sts" {
					http.Error(w, "missing signed gateway headers", http.StatusUnauthorized)
					return
				}
				w.WriteHeader(http.StatusOK)
				_, _ = io.WriteString(w, "accepted")
			}))
			defer server.Close()
			endpoint := server.URL + "/api/v1/gateway/config"
			u, err := url.Parse(endpoint)
			if err != nil {
				t.Fatal(err)
			}
			var headers map[string]string
			if suppliedHostKey != "" {
				headers = map[string]string{suppliedHostKey: u.Host}
			}
			cred := &credential{AccessKeyID: "fixture-ak", SecretAccessKey: "fixture-sk", SecurityToken: "fixture-sts"}
			signed, err := signRequest(http.MethodGet, endpoint, headers, nil, cred, true)
			if err != nil {
				t.Fatal(err)
			}
			req, err := http.NewRequest(http.MethodGet, endpoint, nil)
			if err != nil {
				t.Fatal(err)
			}
			// Keep the direct assignment used by CPA, rather than Header.Set,
			// which would hide incorrectly cased keys by canonicalizing them.
			req.Header = http.Header(toHeaderMap(signed))
			client := server.Client()
			client.Timeout = 2 * time.Second
			resp, err := client.Do(req)
			if err != nil {
				t.Fatal(err)
			}
			defer resp.Body.Close()
			body, err := io.ReadAll(resp.Body)
			if err != nil {
				t.Fatal(err)
			}
			if resp.StatusCode != http.StatusOK || string(body) != "accepted" {
				t.Fatalf("host-signed request rejected after real HTTP serialization: status=%d body=%q", resp.StatusCode, body)
			}
		})
	}
}

// encodeBase64 is a small helper for the lifecycle tests, which must send
// config_yaml in the host's base64 form.
func encodeBase64(data []byte) string {
	return base64.StdEncoding.EncodeToString(data)
}
